# Generated by Django 3.2.5 on 2022-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_auto_20220413_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(max_length=5, null=True, verbose_name='apellido'),
        ),
    ]
