# Generated by Django 3.2.5 on 2022-04-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0005_auto_20220413_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificado',
            field=models.ImageField(null=True, upload_to='certificados'),
        ),
    ]
