# Generated by Django 3.2.5 on 2022-04-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0008_auto_20220413_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=10, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(upload_to='Fotografias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='telefono'),
        ),
    ]
