# Generated by Django 3.2.5 on 2022-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0009_auto_20220413_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aprobado',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
