# Generated by Django 3.2.5 on 2022-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificados'),
        ),
    ]
