# Generated by Django 3.2.5 on 2022-04-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0014_auto_20220413_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('foto_v', models.ImageField(upload_to='vehiculos')),
                ('foto_tarjeta', models.ImageField(upload_to='tarjetapropiedad')),
            ],
        ),
    ]
