# Generated by Django 3.2.5 on 2022-04-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0016_auto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='user',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='ano',
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto_tarjeta',
            field=models.ImageField(upload_to='propiedad'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='placa',
            field=models.CharField(max_length=6),
        ),
    ]
