# Generated by Django 3.2.5 on 2022-04-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0017_auto_20220414_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='nombre',
            new_name='user',
        ),
    ]
