# Generated by Django 3.2.5 on 2022-04-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0018_rename_nombre_auto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='foto_tarjeta',
            field=models.ImageField(null=True, upload_to='propiedad'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto_v',
            field=models.ImageField(null=True, upload_to='vehiculos'),
        ),
    ]
