# Generated by Django 3.2.5 on 2022-04-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0019_auto_20220414_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='foto_tarjeta',
            field=models.ImageField(blank=True, null=True, upload_to='propiedad'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto_v',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
