# Generated by Django 3.2.5 on 2022-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0021_auto_20220414_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_v', models.ImageField(upload_to='vehiculos_fotos')),
            ],
            options={
                'verbose_name': 'automovil',
            },
        ),
    ]
