# Generated by Django 3.2.5 on 2022-04-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0022_automovil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='automovil',
        ),
    ]
