# Generated by Django 3.2.5 on 2022-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0024_auto_20220415_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto_tarjeta',
            field=models.ImageField(null=True, upload_to='propiedad'),
        ),
        migrations.AddField(
            model_name='auto',
            name='foto_v',
            field=models.ImageField(null=True, upload_to='vehiculos'),
        ),
    ]
