# Generated by Django 3.2.5 on 2022-04-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0027_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
