# Generated by Django 3.2.5 on 2022-04-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0028_remove_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
