# Generated by Django 3.2.5 on 2022-04-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0032_auto_aprobado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_inicio', models.CharField(choices=[('Calle', 'Cl'), ('Carrera', 'Cra'), ('Diagonal', 'Dg'), ('Transversal', 'Tr'), ('Avenida', 'Av')], default='Cl', max_length=11)),
                ('cc_ini', models.CharField(max_length=10)),
                ('numero_ini', models.CharField(max_length=10)),
                ('extra_ini', models.CharField(max_length=100)),
                ('direccion_2', models.CharField(choices=[('Calle', 'Cl'), ('Carrera', 'Cra'), ('Diagonal', 'Dg'), ('Transversal', 'Tr'), ('Avenida', 'Av')], default='Cl', max_length=11)),
                ('cc_2', models.CharField(max_length=10)),
                ('numero_2', models.CharField(max_length=10)),
                ('extra_2', models.CharField(max_length=100)),
                ('direccion_3', models.CharField(choices=[('Calle', 'Cl'), ('Carrera', 'Cra'), ('Diagonal', 'Dg'), ('Transversal', 'Tr'), ('Avenida', 'Av')], default='Cl', max_length=11)),
                ('cc_3', models.CharField(max_length=10)),
                ('numero_3', models.CharField(max_length=10)),
                ('extra_3', models.CharField(max_length=100)),
                ('direccion_4', models.CharField(choices=[('Calle', 'Cl'), ('Carrera', 'Cra'), ('Diagonal', 'Dg'), ('Transversal', 'Tr'), ('Avenida', 'Av')], default='Cl', max_length=11)),
                ('cc_4', models.CharField(max_length=10)),
                ('numero_4', models.CharField(max_length=10)),
                ('extra_4', models.CharField(max_length=100)),
                ('direccion_fin', models.CharField(choices=[('Calle', 'Cl'), ('Carrera', 'Cra'), ('Diagonal', 'Dg'), ('Transversal', 'Tr'), ('Avenida', 'Av')], default='Cl', max_length=11)),
                ('cc_fin', models.CharField(max_length=10)),
                ('numero_fin', models.CharField(max_length=10)),
                ('extra_fin', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
