# Generated by Django 3.2.5 on 2022-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0033_auto_20220424_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
