# Generated by Django 3.2.5 on 2022-04-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0034_perfil_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='image',
        ),
    ]
