# Generated by Django 3.2.5 on 2022-04-27 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicaciones', '0039_alter_direccion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
