# Generated by Django 3.2.5 on 2022-04-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0040_alter_direccion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='aprobado_auto',
            field=models.ManyToManyField(blank=True, to='aplicaciones.Autos'),
        ),
    ]
