# Generated by Django 3.2.5 on 2022-04-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0041_direccion_aprobado_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='aprobado_auto',
        ),
    ]
