# Generated by Django 3.2.5 on 2022-04-28 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicaciones', '0043_auto_20220427_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
