# Generated by Django 3.2.5 on 2022-04-28 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicaciones', '0045_auto_20220427_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
